base_station:
  antenna_embedding_dim: 32
  antenna_type: mimo
  num_antennas: 64  # Chrissy has 64 BS antennas (8x8 array)
  antenna_array:
    configuration: "8x8"  # Chrissy has 8x8 BS antenna array
  ofdm:
    bandwidth: 100.0e6  # Chrissy bandwidth: 100 MHz
    center_frequency: 3.7e9  # Chrissy frequency: 3.7 GHz
    fft_size: 512
    guard_band_ratio: 0.0
    num_guard_carriers: 0
    num_subcarriers: 408  # Chrissy has 408 subcarriers
    subcarrier_spacing: 240.0e3  # Chrissy subcarrier spacing: 240 kHz

tracing:
  max_ray_length: 250.0
  num_sampling_points: 16
  use_ipe_encoding: true
  use_mixed_precision: false

input:
  dataset_path: data/chrissy/chrissy.h5  # Chrissy dataset path with 4 UE antennas
  random_seed: 42
  subcarrier_sampling:
    antenna_consistent: true
    sampling_method: uniform
    sampling_ratio: 1
  train_ratio: 0.8
  # Calibration configuration
  calibration:
    enabled: true
    reference_subcarrier_index: 204  # Use second subcarrier (index 1) as reference for PolyU

neural_networks:
  antenna_codebook:
    embedding_dim: 32
    initialization: normal
    normalize: false
    # (Removed) num_bs_antennas should be obtained from base_station, not duplicated here.
    std: 0.1
  attenuation_network:
    activation: relu
    feature_dim: 128
    hidden_dim: 64
    num_layers: 3
    output_dim: 32
    use_shortcuts: true
  csi_network:
    d_model: 64  # Reduced from 256
    n_layers: 2  # Reduced from 4
    n_heads: 4   # Reduced from 16
    d_ff: 256    # Reduced from 1024
    dropout_rate: 0.05
    max_magnitude: 100.0
    # Add frequency domain smoothing for better phase prediction
    smoothing_weight: 0.05  # Moderate smoothing for Chrissy dataset
    smoothing_type: "phase_preserve"  # Preserve magnitude, smooth phase only
  frequency_codebook:
    basis_dim: 32
    initialization: complex_normal
    std: 0.1
    normalize: false
  prism_network:
    antenna_embedding_dim: 32
    azimuth_divisions: 36
    elevation_divisions: 9
  radiance_network:
    activation: relu
    antenna_embedding_dim: 32
    feature_dim: 128
    hidden_dim: 64
    num_layers: 2
    output_dim: 32
    ue_position_dim: 63
    view_direction_dim: 63

output:
  base_dir: results/chrissy
  training:
    checkpoint_dir: '{{base_dir}}/training/checkpoints'
    log_dir: '{{base_dir}}/training/logs'
    log_file: '{{base_dir}}/training/logs/training.log'
    log_level: DEBUG
    models_dir: '{{base_dir}}/training/models'
    tensorboard_dir: '{{base_dir}}/training/tensorboard'

system:
  device: cuda
  fallback_to_cpu: true


training:
  num_epochs: 100
  batch_size: 5  # Minimal batch size to reduce memory usage
  checkpoint_frequency: 5
  enable_gradient_checkpointing: true
  epoch_save_interval: 1
  gradient_accumulation_steps: 1
  learning_rate: 0.00015
  loss:
    csi_loss:
      enabled: true
      magnitude_weight: 1.0
      phase_weight: 3.0
      normalize_weights: true
      max_magnitude: 100.0  # Maximum magnitude for numerical stability
    csi_weight: 1.0
    pdp_loss:
      enabled: false
      fft_size: 512  # Adjusted for 408 subcarriers
      normalize_pdp: true
      type: hybrid
    pdp_weight: 0.5
    regularization_loss:
      enabled: false
    regularization_weight: 0.0
    spatial_spectrum_loss:
      algorithm: bartlett
      enabled: false
      fusion_method: average
      loss_type: ssim
      orientation: bs  # Use BS antenna array (64 antennas) for Chrissy
      phi_range:
      - 0.0
      - 10.0
      - 350.0
      ssim_k1: 0.01
      ssim_k2: 0.03
      ssim_window_size: 11
      ssim_dimension: 1d  # Use 1D SSIM instead of 2D SSIM
      theta_range:
      - 0
      - 5.0
      - 90.0
      # Subcarrier sampling optimization
      num_sampled_subcarriers: 1
      use_covariance_bartlett: false
      use_frequency_dependent_steering: true
    spatial_spectrum_weight: 0.0
  auto_checkpoint: true
  ray_chunk_size: 10
  scaling_factor: 1.0e-15
  weight_decay: 1.0e-05

user_equipment:
  num_ue_antennas: 4  # Chrissy-u4 has 4 UE antennas
  antenna_array:
    configuration: "1x4"  # Chrissy-u4 UE antenna array: 1x4 antennas
  ue_antenna_count: 4  # Number of UE antennas to use (4=antennas 0, 1, 2, and 3)

analysis:
  pas:
    ignore_amplitude: false  # Whether to ignore amplitude and only use phase for spatial spectrum computation
    count: 500  # Maximum number of spatial spectrum samples to analyze (randomly selected from all samples)
    enabled: true  # Enable PAS analysis
    use_parallel: false  # Enable parallel processing for PAS analysis