base_station:
  antenna_embedding_dim: 32
  num_antennas: 64  # Chrissy has 64 BS antennas (8x8 array)
  antenna_array:
    configuration: "8x8"  # 8x8 = 64 antennas total
  ofdm:
    bandwidth: 100.0e6  # Chrissy bandwidth: 100 MHz
    center_frequency: 3.7e9  # Chrissy frequency: 3.7 GHz
    fft_size: 512
    guard_band_ratio: 0.0
    num_guard_carriers: 0
    num_subcarriers: 408  # Chrissy has 408 subcarriers
    subcarrier_spacing: 240.0e3  # Chrissy subcarrier spacing: 240 kHz

tracing:
  max_ray_length: 250.0
  num_sampling_points: 16
  use_ipe_encoding: true
  num_bs_antennas: 64  # Chrissy has 64 BS antennas
  num_subcarriers: 408  # Chrissy has 408 subcarriers
  use_mixed_precision: false

input:
  dataset_path: data/chrissy/chrissy.h5  # Chrissy dataset path
  random_seed: 42
  subcarrier_sampling:
    antenna_consistent: true
    sampling_method: uniform
    sampling_ratio: 1
  train_ratio: 0.8
  # Phase calibration configuration
  phase_calibration:
    enabled: true
    reference_subcarrier_index: 0  # Use first subcarrier (index 0) as reference

neural_networks:
  antenna_codebook:
    embedding_dim: 32
    initialization: normal
    normalize: false
    num_bs_antennas: 64  # Chrissy has 64 BS antennas
    std: 0.1
  csi_network:
    d_model: 256
    n_layers: 4
    n_heads: 16
    d_ff: 1024
    dropout_rate: 0.05
    # Add smoothing regularization
    smoothing_weight: 0.1
    # Add magnitude constraint
    magnitude_constraint: true
    max_magnitude: 100.0
  attenuation_network:
    activation: relu
    feature_dim: 128
    hidden_dim: 64
    num_layers: 3
    output_dim: 32
    use_shortcuts: true
  enabled: true
  frequency_codebook:
    basis_dim: 32
    initialization: complex_normal
    std: 0.1
    normalize: false
  prism_network:
    antenna_embedding_dim: 32
    azimuth_divisions: 18
    elevation_divisions: 6
    num_bs_antennas: 64  # Chrissy has 64 BS antennas
    num_subcarriers: 408  # Chrissy has 408 subcarriers
  radiance_network:
    activation: relu
    antenna_embedding_dim: 32
    feature_dim: 128
    hidden_dim: 64
    num_layers: 2
    output_dim: 32
    ue_position_dim: 63
    view_direction_dim: 63

output:
  base_dir: results/chrissy
  training:
    checkpoint_dir: '{{base_dir}}/training/checkpoints'
    log_dir: '{{base_dir}}/training/logs'
    log_file: '{{base_dir}}/training/logs/training.log'
    log_level: DEBUG
    models_dir: '{{base_dir}}/training/models'
    tensorboard_dir: '{{base_dir}}/training/tensorboard'

system:
  device: cuda
  fallback_to_cpu: true

training:
  num_epochs: 100
  batch_size: 5  # Reduced batch size due to larger antenna array
  checkpoint_frequency: 5
  enable_gradient_checkpointing: true
  epoch_save_interval: 1
  gradient_accumulation_steps: 1
  learning_rate: 0.00015
  loss:
    csi_loss:
      enabled: true
      magnitude_weight: 1.0
      phase_weight: 1.0
      normalize_weights: true
    csi_weight: 1.0
    pdp_loss:
      enabled: false
      fft_size: 512  # Adjusted for 408 subcarriers
      normalize_pdp: true
      type: hybrid
    pdp_weight: 0.0
    regularization_loss:
      enabled: false
    regularization_weight: 0.0
    spatial_spectrum_loss:
      algorithm: bartlett
      enabled: false
      fusion_method: average
      loss_type: ssim
      # Antenna array type: 'bs' for BS array, 'ue' for UE array
      array_type: bs  # Use BS antenna array (64 antennas) for Chrissy
      phi_range:
      - 0.0
      - 10.0
      - 350.0
      ssim_k1: 0.01
      ssim_k2: 0.03
      ssim_window_size: 11
      theta_range:
      - 0
      - 5.0
      - 90.0
      # Subcarrier sampling optimization
      num_sampled_subcarriers: 1
      use_covariance_bartlett: false
      use_frequency_dependent_steering: true
    spatial_spectrum_weight: 0.0
  auto_checkpoint: true
  ray_chunk_size: 10
  scaling_factor: 1.0e-15
  weight_decay: 1.0e-05

user_equipment:
  num_ue_antennas: 1  # Chrissy has 1 UE antenna
  target_antenna_index: 0
