base_station:
  antenna_embedding_dim: 32
  antenna_type: mimo
  num_antennas: 64  # Chrissy has 64 BS antennas (8x8 array)
  antenna_array:
    configuration: "8x8"  # Chrissy has 8x8 BS antenna array
  ofdm:
    bandwidth: 100.0e6  # Chrissy bandwidth: 100 MHz
    center_frequency: 3.7e9  # Chrissy frequency: 3.7 GHz
    num_subcarriers: 408  # Chrissy has 408 subcarriers
    subcarrier_spacing: 240.0e3  # Chrissy subcarrier spacing: 240 kHz

user_equipment:
  num_ue_antennas: 4  # Chrissy-u4 has 4 UE antennas
  antenna_array:
    configuration: "1x4"  # Chrissy-u4 UE antenna array: 1x4 antennas

neural_networks:
  antenna_codebook:
    embedding_dim: 32
    initialization: normal
    normalize: false
    std: 0.1
  attenuation_network:
    activation: relu
    feature_dim: 128
    hidden_dim: 64
    num_layers: 3
    output_dim: 32
    use_shortcuts: true
  csi_network:
    d_model: 16  # Extreme reduction to save memory
    n_layers: 1  # Minimal layers
    n_heads: 1   # Minimal attention heads
    d_ff: 32     # Extreme reduction in feed-forward dimension
    dropout_rate: 0.05
    max_magnitude: 100.0
    # Add frequency domain smoothing for better phase prediction
    smoothing_weight: 0  # No smoothing for memory efficiency
    smoothing_type: "phase_preserve"  # Preserve magnitude, smooth phase only
  frequency_codebook:
    basis_dim: 32
    initialization: complex_normal
    std: 0.1
    normalize: false
  prism_network:
    antenna_embedding_dim: 32
    azimuth_divisions: 18
    elevation_divisions: 6
  radiance_network:
    activation: relu
    antenna_embedding_dim: 32
    feature_dim: 128
    hidden_dim: 64
    num_layers: 2
    output_dim: 32
    ue_position_dim: 16  # Linear projection of 3D UE position to 16D features
    view_direction_dim: 16  # Linear projection of 3D view direction to 16D features

system:
  device: cuda
  fallback_to_cpu: true

tracing:
  max_ray_length: 250.0
  num_sampling_points: 64      # Number of sampling points along each ray (enhanced precision)
  # Ray processing chunk sizes for memory management (high performance mode)
  # IMPORTANT: ray_sub_chunk_size MUST be <= ray_chunk_size and point_chunk_size < num_sampling_points
  # Otherwise will cause tensor dimension mismatch errors!
  ray_chunk_size: 1024        # Main ray processing chunk size (maximum GPU utilization)
  freq_chunk_size: 512        # Frequency processing chunk size (maximum throughput)
  ray_sub_chunk_size: 128     # Ray sub-chunk size (MUST be <= ray_chunk_size)
  point_chunk_size: 56        # Point processing chunk size (MUST be < num_sampling_points=64)

input:
  dataset_path: data/chrissy/chrissy.h5  # Chrissy dataset path with 4 UE antennas
  random_seed: 42
  subcarrier_sampling:
    antenna_consistent: true
    sampling_method: uniform
    sampling_ratio: 1  # Use all subcarriers for full dataset training
  train_ratio: 0.8
  # Position-aware data loading configuration
  use_position_aware_loading: true  # Set to true to enable position-pair-based batching
  # Calibration configuration
  calibration:
    enabled: true
    reference_subcarrier_index: 204  # Use middle subcarrier as reference for Chrissy

output:
  base_dir: results/chrissy
  training:
    checkpoint_dir: '{{base_dir}}/training/checkpoints'
    log_dir: '{{base_dir}}/training/logs'
    log_file: '{{base_dir}}/training/logs/training.log'
    log_level: DEBUG
    models_dir: '{{base_dir}}/training/models'
    tensorboard_dir: '{{base_dir}}/training/tensorboard'

training:
  num_epochs: 50
  batch_size: 300  # Aggressive batch size to maximize GPU utilization (50% → 80% VRAM)
  checkpoint_frequency: 5
  auto_checkpoint: true
  epoch_save_interval: 1
  learning_rate: 0.00015
  weight_decay: 1.0e-05
  lr_scheduler:
    type: 'reduce_on_plateau'
    mode: 'min'
    factor: 0.5          # More aggressive reduction (30% → 50%)
    patience: 2           # Faster response (4 → 2 epochs)
    threshold: 0.001     # More lenient threshold (0.0001 → 0.001)
    threshold_mode: 'rel'
    cooldown: 1
    min_lr_plateau: 0.00001  # Higher minimum LR (0.000005 → 0.00001)
    verbose: true
  loss:
    csi_loss:
      enabled: true
      magnitude_weight: 1.0
      phase_weight: 3.0
      normalize_weights: true
      max_magnitude: 100.0  # Maximum magnitude for numerical stability
    csi_weight: 1.0
    pdp_loss:
      enabled: false
      normalize_pdp: true
      type: hybrid
    pdp_weight: 0.0
    pas_loss:
      enabled: false  # Disable original PAS loss for Chrissy dataset
      azimuth_divisions: 36  # Higher resolution for Chrissy dataset
      elevation_divisions: 9
      normalize_pas: true
      type: mse
      weight_by_power: true
    pas_weight: 0.0
    pas_loss2:
      enabled: true  # Enable PAS Loss 2 for Chrissy dataset
      freq_spatial_weight: 0.40  # Weight for frequency-spatial correlation loss
      phase_consistency_weight: 0.35  # Weight for phase consistency loss
      angle_spectrum_weight: 0.25  # Weight for angle spectrum loss
      lambda_smooth: 0.1  # Smoothing regularization parameter
      mu_eig: 0.1  # Eigenvalue gradient regularization parameter
    pas2_weight: 0.3  # Lower weight for Chrissy dataset
    regularization_loss:
      enabled: false
    regularization_weight: 0.0


analysis:
  pas:
    ignore_amplitude: false  # Whether to ignore amplitude and only use phase for spatial spectrum computation
    count: 5000  # Maximum number of spatial spectrum samples to analyze (randomly selected from all samples)
    enabled: true  # Enable PAS analysis
    use_parallel: false  # Enable parallel processing for PAS analysis