# Configuration for Prism: WiFi Discrete Electromagnetic Ray Tracing
# This configuration implements WiFi ray tracing with MLP-based direction sampling

# Core Ray Tracing Configuration
ray_tracing:
  enabled: true
  azimuth_divisions: 18           # Reduced for WiFi scenarios
  elevation_divisions: 9          # Reduced for WiFi scenarios
  points_per_ray: 16              # Reduced spatial sampling for WiFi
  max_ray_length: 50.0            # Typical WiFi range
  
  # Performance options
  gpu_acceleration: true
  parallel_processing: true

# MLP Direction Sampling Configuration
mlp_direction_sampling:
  enabled: true
  input_dim: 128
  hidden_dim: 64                  # Reduced for WiFi efficiency
  num_hidden_layers: 2
  output_dim: 162                 # 18 × 9 = 162 directions
  target_efficiency: 0.5          # Higher efficiency for WiFi

# RF Signal Processing Configuration
rf_signal_processing:
  enabled: true
  total_subcarriers: 64           # WiFi: 64 subcarriers
  sampling_ratio: 0.5             # 50% sampling for WiFi
  frequency_band: 2.4e9           # 2.4 GHz WiFi
  subcarrier_spacing: 312.5e3     # 312.5 kHz spacing

# Base Station Configuration
base_station:
  default_position: [0.0, 0.0, 2.5]  # WiFi AP height
  num_antennas: 4                     # WiFi AP antennas
  antenna_embedding_dim: 128

# Performance Configuration
performance:
  device: 'cuda'
  batch_size: 64                  # Smaller batches for WiFi
  max_concurrent_rays: 200
