# Configuration for Prism: Neural Network-Based Electromagnetic Ray Tracing System
# This configuration implements the updated ray tracing design with neural networks

# Core Ray Tracing Configuration
ray_tracing:
  # Enable ray tracing system
  enabled: true
  
  # Angular sampling (configurable)
  azimuth_divisions: 36           # Number of azimuth divisions A (0° to 360°)
  elevation_divisions: 18         # Number of elevation divisions B (-90° to +90°)
  
  # Spatial sampling (configurable)
  uniform_samples: 128            # First stage: uniform sampling points per ray
  resampled_points: 128            # Second stage: importance-based resampled points
  
  # Coverage calculations
  total_directions: 648           # 36 × 18 = 648 angle combinations
  total_spatial_points: 41472     # 648 × 64 = 41,472 spatial samples
  
  # Resolution settings
  azimuth_resolution: 10          # 10° between azimuth samples
  elevation_resolution: 10        # 10° between elevation samples
  
  # Physical parameters
  max_ray_length: 100.0           # Maximum ray length in meters
  scene_size: 200.0               # Scene size D (cubic environment)
  
  # Performance options
  gpu_acceleration: true          # Enable GPU acceleration
  enable_early_termination: true  # Enable early termination optimization
  signal_threshold: 1e-6          # Signal strength threshold for early termination

# Neural Network Configuration
neural_networks:
  # Enable neural network-based processing
  enabled: true
  
  # Attenuation Network
  attenuation_network:
    input_dim: 3                  # 3D spatial position
    hidden_dim: 256               # Hidden layer dimension
    num_hidden_layers: 8          # Number of hidden layers
    feature_dim: 128              # Output feature dimension
    activation: 'relu'            # Activation function
    use_shortcut: true            # Enable shortcut connections
    
  # Attenuation Decoder
  attenuation_decoder:
    input_dim: 128                # Feature dimension from AttenuationNetwork
    hidden_dim: 256               # Hidden layer dimension
    num_hidden_layers: 3          # Number of hidden layers
    output_dim: 408               # Number of subcarriers K
    num_ue: 1000                  # Number of UE devices
    activation: 'relu'            # Activation function
    
  # Antenna Codebook
  antenna_codebook:
    num_antennas: 64              # Number of BS antennas N_BS
    embedding_dim: 64             # Antenna embedding dimension
    learnable: true               # Learnable embeddings
    
  # Antenna Network (MLP-based direction sampling)
  antenna_network:
    input_dim: 64                 # Antenna embedding dimension
    hidden_dim: 128               # Hidden layer dimension
    num_hidden_layers: 2          # Number of hidden layers
    output_dim: 648               # A × B directions (36 × 18 = 648)
    activation: 'relu'            # Activation function
    dropout_rate: 0.1             # Dropout rate for regularization
    
  # Radiance Network
  radiance_network:
    ue_pos_dim: 3                 # UE position dimension
    view_dir_dim: 3               # Viewing direction dimension
    spatial_feature_dim: 128      # Spatial feature dimension
    antenna_embedding_dim: 64     # Antenna embedding dimension
    hidden_dim: 256               # Hidden layer dimension
    num_hidden_layers: 4          # Number of hidden layers
    output_dim: 408               # Number of subcarriers K
    num_ue: 1000                  # Number of UE devices
    activation: 'relu'            # Activation function

# RF Signal Processing Configuration
rf_signal_processing:
  # Enable RF signal processing
  enabled: true
  
  # Subcarrier configuration
  total_subcarriers: 408          # Total number of subcarriers K
  sampling_ratio: 0.3             # Subcarrier sampling ratio α (30%)
  selected_subcarriers: 122       # K' = α × K = 0.3 × 408 = 122
  
  # Frequency configuration
  frequency_band: 2.4e9           # Center frequency (2.4 GHz)
  subcarrier_spacing: 15e3        # Subcarrier spacing (15 kHz)
  
  # Signal processing options
  enable_path_loss_calculation: true
  enable_antenna_factor: true
  enable_material_attenuation: true

# Base Station Configuration
base_station:
  # Default configuration
  default_position: [0.0, 0.0, 0.0]  # Base station at origin
  num_antennas: 64                     # Number of BS antennas
  antenna_embedding_dim: 64            # Antenna embedding dimension
  
  # Antenna properties
  antenna_type: 'mimo'                 # MIMO antenna configuration
  polarization: 'dual'                 # Dual polarization support

# User Equipment Configuration
user_equipment:
  # UE configuration
  num_ue: 1000                         # Number of UE devices
  antenna_config: '4x4'                # 4 UE antennas per device
  
  # Position distribution
  position_range: [-100.0, 100.0]      # UE position range in meters
  height_range: [1.0, 2.0]             # UE height range in meters

# Importance Sampling Configuration
importance_sampling:
  # Enable importance-based sampling
  enabled: true
  
  # Sampling parameters
  power_factor: 2.0                # Power factor for weight calculation
  min_weights: 1e-6                # Minimum weight threshold
  normalize_weights: true          # Normalize importance weights
  
  # Resampling parameters
  resampling_method: 'multinomial' # Resampling method
  replacement: true                 # Allow replacement during resampling

# Performance Configuration
performance:
  # Computational settings
  device: 'cuda'                       # Device for computation ('cuda' or 'cpu')
  batch_size: 256                      # Batch size for processing
  max_concurrent_rays: 1000            # Maximum concurrent rays
  
  # Memory management
  gpu_memory_fraction: 0.8             # GPU memory usage fraction
  enable_mixed_precision: true         # Enable mixed precision for efficiency
  
  # Parallel processing
  num_workers: 4                       # Number of parallel workers
  enable_distributed: false            # Enable distributed processing

# Output Configuration
output:
  # Results storage
  save_results: true                   # Save ray tracing results
  output_format: 'hdf5'                # Output file format
  compression_level: 6                 # Compression level for output files
  
  # Logging
  log_level: 'INFO'                    # Logging level
  enable_progress_bar: true            # Enable progress bars
  save_training_history: true          # Save neural network training history
