# Configuration for Prism: Discrete Electromagnetic Ray Tracing System
# This configuration implements the new ray tracing design with MLP-based direction sampling

# Core Ray Tracing Configuration
ray_tracing:
  # Enable ray tracing system
  enabled: true
  
  # Angular sampling (configurable)
  azimuth_divisions: 36           # Number of azimuth divisions A (0° to 360°)
  elevation_divisions: 18         # Number of elevation divisions B (-90° to +90°)
  
  # Spatial sampling (configurable)
  points_per_ray: 64              # Spatial sampling points per ray
  
  # Coverage calculations
  total_directions: 648           # 36 × 18 = 648 angle combinations
  total_spatial_points: 41472     # 648 × 64 = 41,472 spatial samples
  
  # Resolution settings
  azimuth_resolution: 10          # 10° between azimuth samples
  elevation_resolution: 10        # 10° between elevation samples
  spatial_resolution: 0.1         # 0.1m between spatial points
  
  # Physical parameters
  max_ray_length: 100.0           # Maximum ray length in meters
  reflection_order: 3             # Maximum reflection order
  diffraction_enabled: true       # Enable diffraction effects
  scattering_enabled: true        # Enable scattering effects
  
  # Performance options
  gpu_acceleration: true          # Enable GPU acceleration
  parallel_processing: true       # Enable parallel processing
  memory_optimization: true       # Enable memory optimization

# MLP Direction Sampling Configuration
mlp_direction_sampling:
  # Enable MLP-based direction sampling
  enabled: true
  
  # MLP architecture
  input_dim: 128                  # Antenna embedding dimension
  hidden_dim: 256                 # Hidden layer dimension
  num_hidden_layers: 2            # Number of hidden layers (2-3 as per design)
  output_dim: 648                 # A × B directions (36 × 18 = 648)
  
  # Training parameters
  learning_rate: 0.001            # Learning rate for training
  batch_size: 32                  # Batch size for training
  num_epochs: 100                 # Number of training epochs
  dropout_rate: 0.1               # Dropout rate for regularization
  threshold: 0.5                  # Threshold for binary indicators
  
  # Sampling efficiency
  target_efficiency: 0.3          # Target sampling efficiency (30% of directions)

# RF Signal Processing Configuration
rf_signal_processing:
  # Enable RF signal processing
  enabled: true
  
  # Subcarrier configuration
  total_subcarriers: 408          # Total number of subcarriers K
  sampling_ratio: 0.3             # Subcarrier sampling ratio α (30%)
  selected_subcarriers: 122       # K' = α × K = 0.3 × 408 = 122
  
  # Frequency configuration
  frequency_band: 2.4e9           # Center frequency (2.4 GHz)
  subcarrier_spacing: 15e3        # Subcarrier spacing (15 kHz)
  
  # Signal processing options
  enable_path_loss_calculation: true
  enable_antenna_factor: true
  enable_material_attenuation: true

# Base Station Configuration
base_station:
  # Default configuration
  default_position: [0.0, 0.0, 0.0]  # Base station at origin
  num_antennas: 64                     # Number of BS antennas
  antenna_embedding_dim: 128           # Antenna embedding dimension
  
  # Antenna properties
  antenna_type: 'mimo'                 # MIMO antenna configuration
  polarization: 'dual'                 # Dual polarization support

# User Equipment Configuration
user_equipment:
  # UE configuration
  num_ue: 1000                         # Number of UE devices
  antenna_config: '4x4'                # 4 UE antennas per device
  
  # Position distribution
  position_range: [-100.0, 100.0]      # UE position range in meters
  height_range: [1.0, 2.0]             # UE height range in meters

# Environment Configuration
environment:
  # Voxel grid configuration
  voxel_grid_size: [200, 200, 50]     # Grid dimensions (nx, ny, nz)
  voxel_size: 1.0                      # Voxel size in meters
  
  # Material properties
  materials:
    concrete:
      permittivity: 4.5
      conductivity: 0.02
      attenuation_coeff: 0.1
    glass:
      permittivity: 3.8
      conductivity: 0.0
      attenuation_coeff: 0.05
    metal:
      permittivity: 1.0
      conductivity: 1e7
      attenuation_coeff: 0.8
    wood:
      permittivity: 2.0
      conductivity: 0.01
      attenuation_coeff: 0.08
    plastic:
      permittivity: 2.3
      conductivity: 0.0
      attenuation_coeff: 0.06

# Performance Configuration
performance:
  # Computational settings
  device: 'cuda'                       # Device for computation ('cuda' or 'cpu')
  batch_size: 256                      # Batch size for processing
  max_concurrent_rays: 1000            # Maximum concurrent rays
  
  # Memory management
  gpu_memory_fraction: 0.8             # GPU memory usage fraction
  enable_mixed_precision: true         # Enable mixed precision for efficiency
  
  # Parallel processing
  num_workers: 4                       # Number of parallel workers
  enable_distributed: false            # Enable distributed processing

# Output Configuration
output:
  # Results storage
  save_results: true                   # Save ray tracing results
  output_format: 'hdf5'                # Output file format
  compression_level: 6                 # Compression level for output files
  
  # Logging
  log_level: 'INFO'                    # Logging level
  enable_progress_bar: true            # Enable progress bars
  save_training_history: true          # Save MLP training history
