# Configuration for Prism: Wideband Discrete Electromagnetic Ray Tracing
# This configuration implements wideband ray tracing with MLP-based direction sampling

# Core Ray Tracing Configuration
ray_tracing:
  enabled: true
  azimuth_divisions: 24           # Reduced for wideband processing
  elevation_divisions: 12         # Reduced for wideband processing
  points_per_ray: 32              # Reduced spatial sampling
  max_ray_length: 200.0           # Extended for wideband scenarios
  
  # Performance options
  gpu_acceleration: true
  parallel_processing: true

# MLP Direction Sampling Configuration
mlp_direction_sampling:
  enabled: true
  input_dim: 128
  hidden_dim: 128                 # Reduced for efficiency
  num_hidden_layers: 2
  output_dim: 288                 # 24 × 12 = 288 directions
  target_efficiency: 0.4          # Higher efficiency for wideband

# RF Signal Processing Configuration
rf_signal_processing:
  enabled: true
  total_subcarriers: 1024         # Wideband: 1024 subcarriers
  sampling_ratio: 0.2             # 20% sampling for efficiency
  frequency_band: 6e9             # 6 GHz wideband
  subcarrier_spacing: 30e3        # 30 kHz spacing

# Base Station Configuration
base_station:
  default_position: [0.0, 0.0, 0.0]
  num_antennas: 32                # Reduced for wideband
  antenna_embedding_dim: 128

# Performance Configuration
performance:
  device: 'cuda'
  batch_size: 128                 # Smaller batches for wideband
  max_concurrent_rays: 500
