base_station:
  antenna_embedding_dim: 32
  antenna_type: mimo
  num_antennas: 1  # PolyU has 1 BS antenna
  antenna_array:
    configuration: "1x1"  # PolyU has 1 BS antenna
    spacing_x: 0.0625  # Antenna spacing in x direction (half wavelength at 2.4 GHz)
    spacing_y: 0.0625  # Antenna spacing in y direction (half wavelength at 2.4 GHz)
  ofdm:
    bandwidth: 20.0e6  # PolyU WiFi bandwidth: 20 MHz
    center_frequency: 2.4e9  # PolyU WiFi frequency: 2.4 GHz
    fft_size: 64
    guard_band_ratio: 0.0
    num_guard_carriers: 0
    num_subcarriers: 64  # PolyU has 64 subcarriers
    subcarrier_spacing: 312.5e3  # PolyU WiFi subcarrier spacing: 312.5 kHz

user_equipment:
  num_ue_antennas: 8  # PolyU has 8 UE antennas
  antenna_array:
    configuration: "2x4"  # PolyU UE antenna array: 2 rows x 4 columns
    spacing_x: 0.0625  # Antenna spacing in x direction (half wavelength at 2.4 GHz)
    spacing_y: 0.0625  # Antenna spacing in y direction (half wavelength at 2.4 GHz)
  ue_antenna_count: 8  # Number of UE antennas to use (1=antenna 0, 2=antennas 0,1, 3=antennas 0,1,2, etc.)

neural_networks:
  antenna_codebook:
    embedding_dim: 32
    initialization: normal
    normalize: false
    std: 0.1
  attenuation_network:
    activation: relu
    feature_dim: 128
    hidden_dim: 64
    num_layers: 3
    output_dim: 32
    use_shortcuts: true
  csi_network:
    d_model: 128
    n_layers: 2
    n_heads: 8
    d_ff: 512
    dropout_rate: 0.1
    max_magnitude: 50.0
    # Add frequency domain smoothing for better phase prediction
    smoothing_weight: 0  # Lower smoothing weight for PolyU dataset
    smoothing_type: "phase_preserve"  # Preserve magnitude, smooth phase only
  frequency_codebook:
    basis_dim: 32
    initialization: complex_normal
    std: 0.1
    normalize: false
  prism_network:
    antenna_embedding_dim: 32
    azimuth_divisions: 18
    elevation_divisions: 6
  radiance_network:
    activation: relu
    antenna_embedding_dim: 32
    feature_dim: 128
    hidden_dim: 64
    num_layers: 2
    output_dim: 32
    ue_position_dim: 63
    view_direction_dim: 63

system:
  device: cuda
  fallback_to_cpu: true

tracing:
  max_ray_length: 250.0
  num_sampling_points: 16
  use_ipe_encoding: true
  use_mixed_precision: false
  # Ray processing chunk sizes for memory management
  ray_chunk_size: 128         # Main ray processing chunk size (default for PolyU)
  freq_chunk_size: 16         # Frequency processing chunk size (default)
  ray_sub_chunk_size: 8       # Ray sub-chunk size (default)
  point_chunk_size: 8         # Point processing chunk size (default)

input:
  dataset_path: data/polyu/polyu_syn.h5  # PolyU dataset path (reorganized CSI structure)
  random_seed: 42
  subcarrier_sampling:
    antenna_consistent: true
    sampling_method: uniform
    sampling_ratio: 1
  train_ratio: 0.8
  # Calibration configuration
  calibration:
    enabled: true
    reference_subcarrier_index: 1  # Use second subcarrier (index 1) as reference for PolyU

output:
  base_dir: results/polyu
  training:
    checkpoint_dir: '{{base_dir}}/training/checkpoints'
    log_dir: '{{base_dir}}/training/logs'
    log_file: '{{base_dir}}/training/logs/training.log'
    log_level: DEBUG
    models_dir: '{{base_dir}}/training/models'
    tensorboard_dir: '{{base_dir}}/training/tensorboard'

training:
  num_epochs: 50  # Reduced epochs for PolyU dataset
  batch_size: 8
  checkpoint_frequency: 10
  enable_gradient_checkpointing: true
  epoch_save_interval: 1
  gradient_accumulation_steps: 1
  learning_rate: 0.00015
  lr_scheduler:
    type: 'reduce_on_plateau'
    mode: 'min'
    factor: 0.5          # More aggressive reduction (30% → 50%)
    patience: 2           # Faster response (4 → 2 epochs)
    threshold: 0.001     # More lenient threshold (0.0001 → 0.001)
    threshold_mode: 'rel'
    cooldown: 1
    min_lr_plateau: 0.00001  # Higher minimum LR (0.000005 → 0.00001)
    verbose: true
  loss:
    csi_loss:
      enabled: true
      magnitude_weight: 1.0
      phase_weight: 2.0
      normalize_weights: true
      max_magnitude: 50.0  # Maximum magnitude for numerical stability
    csi_weight: 1.0
    pdp_loss:
      enabled: false
      fft_size: 128  # Adjusted for 64 subcarriers
      normalize_pdp: true
      type: hybrid
    pdp_weight: 0.0
    regularization_loss:
      enabled: false
    regularization_weight: 0.0
  auto_checkpoint: true
  ray_chunk_size: 10
  scaling_factor: 1.0e-9
  weight_decay: 1.0e-05

analysis:
  pas:
    ignore_amplitude: false  # Whether to ignore amplitude and only use phase for spatial spectrum computation
    count: 500  # Maximum number of spatial spectrum samples to analyze (randomly selected from all samples)
    enabled: true  # Enable PAS analysis
    use_parallel: false  # Enable parallel processing for PAS analysis