base_station:
  antenna_embedding_dim: 32
  antenna_type: mimo
  num_antennas: 1  # PolyU has 1 BS antenna
  antenna_array:
    configuration: "1x1"  # PolyU has 1 BS antenna
  ofdm:
    bandwidth: 20.0e6  # PolyU WiFi bandwidth: 20 MHz
    center_frequency: 2.4e9  # PolyU WiFi frequency: 2.4 GHz
    num_subcarriers: 64  # PolyU has 64 subcarriers
    subcarrier_spacing: 312.5e3  # PolyU WiFi subcarrier spacing: 312.5 kHz

user_equipment:
  num_ue_antennas: 8  # PolyU has 8 UE antennas
  antenna_array:
    configuration: "2x4"  # PolyU UE antenna array: 2 rows x 4 columns

neural_networks:
  antenna_codebook:
    embedding_dim: 32
    initialization: normal
    normalize: false
    std: 0.1
  attenuation_network:
    activation: relu
    feature_dim: 128
    hidden_dim: 64
    num_layers: 3
    output_dim: 32
    use_shortcuts: true
  csi_network:
    d_model: 128
    n_layers: 4
    n_heads: 8
    d_ff: 512
    dropout_rate: 0.05
    max_magnitude: 50.0
    # Add frequency domain smoothing for better phase prediction
    smoothing_weight: 0  # Lower smoothing weight for PolyU dataset
    smoothing_type: "phase_preserve"  # Preserve magnitude, smooth phase only
  frequency_codebook:
    basis_dim: 32
    initialization: complex_normal
    std: 0.1
    normalize: false
  prism_network:
    antenna_embedding_dim: 32
    azimuth_divisions: 18
    elevation_divisions: 6
  radiance_network:
    activation: relu
    antenna_embedding_dim: 32
    feature_dim: 128
    hidden_dim: 64
    num_layers: 2
    output_dim: 32
    ue_position_dim: 16  # Linear projection of 3D UE position to 16D features
    view_direction_dim: 16  # Linear projection of 3D view direction to 16D features

system:
  device: cuda
  fallback_to_cpu: true

tracing:
  max_ray_length: 250.0
  num_sampling_points: 64
  # Ray processing chunk sizes for memory management
  # IMPORTANT: ray_sub_chunk_size MUST be <= ray_chunk_size and point_chunk_size < num_sampling_points
  # Otherwise will cause tensor dimension mismatch errors!
  ray_chunk_size: 1024         # Main ray processing chunk size (default for PolyU)
  freq_chunk_size: 512         # Frequency processing chunk size (default)
  ray_sub_chunk_size: 128       # Ray sub-chunk size (MUST be <= ray_chunk_size)
  point_chunk_size: 56         # Point processing chunk size (MUST be < num_sampling_points)

input:
  dataset_path: data/polyu/polyu_syn.h5  # PolyU dataset path (reorganized CSI structure)
  random_seed: 42
  subcarrier_sampling:
    antenna_consistent: true
    sampling_method: uniform
    sampling_ratio: 1
  train_ratio: 0.8
  # Position-aware data loading configuration
  use_position_aware_loading: true  # Set to true to enable position-pair-based batching
  # Calibration configuration
  calibration:
    enabled: true
    reference_subcarrier_index: 1  # Use second subcarrier (index 1) as reference for PolyU

output:
  base_dir: results/polyu
  training:
    checkpoint_dir: '{{base_dir}}/training/checkpoints'
    log_dir: '{{base_dir}}/training/logs'
    log_file: '{{base_dir}}/training/logs/training.log'
    log_level: DEBUG
    models_dir: '{{base_dir}}/training/models'
    tensorboard_dir: '{{base_dir}}/training/tensorboard'
    debug_dir: '{{base_dir}}/training/debug'      # Debug directory for temporary spatial spectrum and intermediate files

training:
  num_epochs: 60  # Reduced epochs for PolyU dataset
  batch_size: 16  # Position pairs per batch (16 pairs × 8 antenna combinations = 128 samples)
  checkpoint_frequency: 5
  auto_checkpoint: true
  epoch_save_interval: 1
  learning_rate: 0.0003  # Adjusted for position-aware batching (16 position pairs)
  weight_decay: 1.0e-06  # Reduced from 1.0e-05 to allow more dynamic range
  lr_scheduler:
    type: 'reduce_on_plateau'
    mode: 'min'
    factor: 0.5          # More aggressive reduction (30% → 50%)
    patience: 2           # Faster response (4 → 2 epochs)
    threshold: 0.001     # More lenient threshold (0.0001 → 0.001)
    threshold_mode: 'rel'
    cooldown: 1
    min_lr_plateau: 0.00001  # Higher minimum LR (0.000005 → 0.00001)
    verbose: true
  loss:
    csi_loss:
      enabled: true
      magnitude_weight: 1.2
      phase_weight: 3.0
      normalize_weights: true
      max_magnitude: 50.0  # Maximum magnitude for numerical stability
    csi_weight: 1.0
    pdp_loss:
      enabled: false
      fft_size: 2048  # Adjusted for 64 subcarriers
      normalize_pdp: true
      type: hybrid
    pdp_weight: 1.0
    pas_loss:
      enabled: true  # Set to false to disable original PAS loss
      azimuth_divisions: 18  # ~20 degree resolution (180/18 = 10 deg per bin)
      elevation_divisions: 6   # 15 degree resolution (90/6 = 15 deg per bin)
      normalize_pas: false  # Disable normalization for larger loss values
      type: mse  # 'mse', 'mae', 'kl_div', 'js_div'
      weight_by_power: false  # Disable power weighting for simplicity
    pas_weight: 1.0
    pas2_loss:
      enabled: false  # Enable PAS Loss 2 (Multi-subcarrier CSI Spatial-Frequency Loss)
      freq_spatial_weight: 0.40  # Weight for frequency-spatial correlation loss
      phase_consistency_weight: 0.35  # Weight for phase consistency loss
      angle_spectrum_weight: 0.25  # Weight for angle spectrum loss
      lambda_smooth: 0.1  # Smoothing regularization parameter
      mu_eig: 0.1  # Eigenvalue gradient regularization parameter
    pas2_weight: 0.03
    regularization_loss:
      enabled: false
    regularization_weight: 0.0


analysis:
  pas:
    ignore_amplitude: false  # Whether to ignore amplitude and only use phase for spatial spectrum computation
    count: 50000  # Maximum number of spatial spectrum samples to analyze (randomly selected from all samples)
    enabled: true  # Enable PAS analysis
    use_parallel: false  # Enable parallel processing for PAS analysis